" Setup indentation with 4 spaces for tabs
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab


" By default .tex files have plain TeX flavour. Change this to LaTeX.
let g:tex_flavor='latex'


" Fix backspace behaviour
set backspace=indent,eol,start

" Plugins like gitgutter tend to be slower with other shells like fish, so
" we'll force Vim/NeoVim to use bash.
set shell=/bin/bash


" Draw color column at 80 lines, set line length limit to be at the same point
highlight ColorColumn ctermbg=Black
set colorcolumn=80
set textwidth=79


" Only draw colorcolumn in the current split
function! OnWinEnter()
    if exists('b:colorcolumn_old')
        let &colorcolumn=b:colorcolumn_old
    endif
endfunction
function! OnWinLeave()
	let b:colorcolumn_old=&colorcolumn
	set colorcolumn=0
endfunction
augroup BgHighlight
    autocmd!
    autocmd WinEnter * call OnWinEnter()
    autocmd WinLeave * call OnWinLeave()
augroup END<Paste>


" Set larger line length limit for some file types
autocmd FileType javascript.jsx setlocal colorcolumn=120
autocmd FileType javascript.jsx setlocal textwidth=119


" Check matching bracket highlighting
highlight MatchParen cterm=none ctermbg=magenta ctermfg=black


" Set Search highlight color
highlight Search cterm=none ctermbg=black ctermfg=magenta


" Change split separator symbol and color to make it less intrusive
set fillchars=vert:┃
set fillchars+=stl:━
set fillchars+=stlnc:━
highlight VertSplit cterm=none ctermbg=none ctermfg=white


" Make sure statusline is not inverted (to make it less intrusive)
highlight StatusLine term=bold cterm=bold ctermfg=Black
highlight StatusLineNC term=none cterm=none ctermfg=Black


" Enable line numbers and make them very dim
set nu
highlight LineNr ctermfg=black


" Install vim-plug if it isn't already installed 
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" vim-plug plugins
call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
Plug 'w0rp/ale'
Plug 'airblade/vim-gitgutter'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'

call plug#end()


" Set Ale color scheme
highlight ALEError ctermbg=red


" Some vimtex features require Vim to be compiled with certain flags. This is
" not always possible, so we just disable them.
let g:vimtex_compiler_latexmk = {'callback' : 0}

