" Setup indentation with 4 spaces for tabs
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab


" By default .tex files have plain TeX flavour. Change this to LaTeX.
let g:tex_flavor='latex'


" Fix backspace behaviour
set backspace=indent,eol,start


" Plugins like gitgutter tend to be slower with other shells like fish, so
" we'll force Vim/NeoVim to use bash.
set shell=/bin/bash


" Draw color column at 80 lines
set colorcolumn=80
highlight ColorColumn ctermbg=Black


" Make sure statusline is not inverted (to make it less intrusive)
highlight StatusLine term=bold cterm=bold ctermfg=Black gui=bold


" Enable line numbers and make them very dim
set nu
highlight LineNr ctermfg=black


" Install vim-plug if it isn't already installed 
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" vim-plug plugins
call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
Plug 'w0rp/ale'
Plug 'airblade/vim-gitgutter'

call plug#end()

" Some vimtex features require Vim to be compiled with certain flags. This is
" not always possible, so we just disable them.
let g:vimtex_compiler_latexmk = {'callback' : 0}

