" Setup indentation with 4 spaces for tabs
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

" By default .tex files have plain TeX flavour
let g:tex_flavor='latex'

" Draw color column at 80 lines
set colorcolumn=80
highlight ColorColumn ctermbg=Black

" Enable line numbers and make them very dim
set nu
highlight LineNr ctermfg=black
